# Generated by Django 5.2.7 on 2026-06-18 01:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dljw6q0yq/image/upload/v1777041924/profilepicture_mae8dg.jpg', max_length=255, null=True, verbose_name='Profile Picture'),
        ),
    ]
